dbfilename redis_queue.rdb
dir /home/azizul-hoq/frappe/erp-service/config/pids
pidfile /home/azizul-hoq/frappe/erp-service/config/pids/redis_queue.pid
bind 127.0.0.1
port 11001

aclfile /home/azizul-hoq/frappe/erp-service/config/redis_queue.acl
